name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -e .[dev] 
        pip install pytest 
        pip install pyarrow h5py

    - name: Run tests with coverage & benchmarks
      run: pytest 

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     fail_ci_if_error: true
    #     file: ./coverage.xml
    #     token: ${{ secrets.CODECOV_TOKEN }}

    # - name: Store benchmark result
    #   uses: benchmark-action/github-action-benchmark@v1
    #   with:
    #     tool: 'pytest'
    #     output-file-path: benchmark_result.json
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     auto-push: true